name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Se ejecuta solo cuando confirmas cambios en master

# Configura los permisos necesarios para interactuar con GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evita ejecuciones simultáneas del mismo flujo para no pisar despliegues
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11 # Forzamos la versión 11 que tienes configurada

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Una versión LTS estable y moderna
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Indicamos que suba el contenido de la carpeta donde se genera tu compilado
          path: "${{ github.workspace }}/dist/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
